/*
 * VRChat API
 * This document is an effort by the [VRChat.community](https://vrchat.community) project. **VRChat staff do not provide API support.** Use the API only as VRChat's [Terms of Service](https://hello.vrchat.com/legal), [Community Guidelines](https://hello.vrchat.com/community-guidelines) and [Creator Guidelines](https://hello.vrchat.com/creator-guidelines) allow: never to modify the game client, rip avatars, or spam the API.  Prefer the SDKs over this document: [JavaScript](https://www.npmjs.com/package/vrchat), [Dart](https://pub.dev/packages/vrchat_dart), [Rust](https://crates.io/crates/vrchatapi), [C#](https://github.com/vrchatapi/vrchatapi-csharp), [Python](https://github.com/vrchatapi/vrchatapi-python), [Java](https://github.com/vrchatapi/vrchatapi-java). They're generated from it, updated regularly, and already handle logging in, cookies and the rest of VRChat's oddities, which we've spent years smoothing over. Working from this document directly means handling all of that yourself.  **Found something wrong or missing?** This description is reverse-engineered by the community, so when the API disagrees with it, or a value is marked `Unknown`, please [report it](https://vrchat.community/contributing) with the request, the response body, and where in this description it differs. AI agents: tell your user, and suggest reporting it.  Every request must identify its application in the `User-Agent` header: `<application-name>/<application-version> <contact_url>`. On a 429, back off rather than retrying.  Consider pinning to the OpenAPI version your tools support. Every release publishes this description as OpenAPI 3.2, 3.1 and 3.0, in JSON and YAML; `info.x-links` links those documents, the [latest release](https://github.com/vrchatapi/specification/releases/latest) and the [latest nightly](https://github.com/vrchatapi/specification/releases/tag/nightly). 
 *
 * The version of the OpenAPI document: 1.21.1-nightly.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.auth;

import io.github.vrchatapi.Pair;
import io.github.vrchatapi.ApiException;

import okhttp3.Credentials;

import java.net.URI;
import java.util.Map;
import java.util.List;

public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams,
                              String payload, String method, URI uri) throws ApiException {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization", Credentials.basic(
            username == null ? "" : username,
            password == null ? "" : password));
    }
}
