on:
  push:
    branches:
      - '**'
  pull_request:
  repository_dispatch:
    types: [release]
  workflow_dispatch:
    inputs:
      json:
        description: Passed json from repository_dispatch
        required: true
        type: string
      version_postfix:
        description: Additional string to concatenate onto the existing version before release
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: CI

env:
  PASSED_VERSION: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload || fromJSON(inputs.json || '{}'))['version'] }}
  VERSION_POSTPEND: ${{ github.event_name == 'workflow_dispatch' && inputs.version_postfix || '' }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-java
          ref: ${{ inputs.ref || github.ref }}

      - uses: vrchatapi/specification/.github/actions/setup-generator@main

      - uses: vrchatapi/specification/.github/actions/download@main
        with:
          bundle: openapi-legacy.yaml

      - if: env.VERSION_POSTPEND != ''
        run: yq '--inplace' ".info.version |= \"${PASSED_VERSION}${VERSION_POSTPEND}\"" openapi-legacy.yaml

      - run: bash ./generate.sh openapi-legacy.yaml

      - uses: actions/upload-artifact@v7
        with:
          name: java-generated
          path: |
            .
            !.git/**
          include-hidden-files: true

  test:
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17', '21']
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: java-generated

      - uses: actions/setup-java@v5.7.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - run: mvn -B package --no-transfer-progress

  publish:
    needs:
      - generate
      - test
    if: github.repository == 'vrchatapi/vrchatapi-java'
      && (github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-java

      - uses: actions/download-artifact@v8
        with:
          name: java-generated

      - run: rm -f openapi-legacy.yaml

      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: main
          folder: .
          commit-message: Upgrade Java SDK to spec ${{ env.PASSED_VERSION }}${{ env.VERSION_POSTPEND }}
          tag: ${{ env.PASSED_VERSION }}${{ env.VERSION_POSTPEND }}
