/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.9
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.vrchatapi.model.AvatarModerationType;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * AvatarModeration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AvatarModeration {
  public static final String SERIALIZED_NAME_AVATAR_MODERATION_TYPE = "avatarModerationType";
  @SerializedName(SERIALIZED_NAME_AVATAR_MODERATION_TYPE)
  @javax.annotation.Nonnull
  private AvatarModerationType avatarModerationType;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nonnull
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_TARGET_AVATAR_ID = "targetAvatarId";
  @SerializedName(SERIALIZED_NAME_TARGET_AVATAR_ID)
  @javax.annotation.Nonnull
  private String targetAvatarId;

  public AvatarModeration() {
  }

  public AvatarModeration avatarModerationType(@javax.annotation.Nonnull AvatarModerationType avatarModerationType) {
    this.avatarModerationType = avatarModerationType;
    return this;
  }

  /**
   * Get avatarModerationType
   * @return avatarModerationType
   */
  @javax.annotation.Nonnull
  public AvatarModerationType getAvatarModerationType() {
    return avatarModerationType;
  }

  public void setAvatarModerationType(@javax.annotation.Nonnull AvatarModerationType avatarModerationType) {
    this.avatarModerationType = avatarModerationType;
  }


  public AvatarModeration created(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
  }


  public AvatarModeration targetAvatarId(@javax.annotation.Nonnull String targetAvatarId) {
    this.targetAvatarId = targetAvatarId;
    return this;
  }

  /**
   * Get targetAvatarId
   * @return targetAvatarId
   */
  @javax.annotation.Nonnull
  public String getTargetAvatarId() {
    return targetAvatarId;
  }

  public void setTargetAvatarId(@javax.annotation.Nonnull String targetAvatarId) {
    this.targetAvatarId = targetAvatarId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvatarModeration avatarModeration = (AvatarModeration) o;
    return Objects.equals(this.avatarModerationType, avatarModeration.avatarModerationType) &&
        Objects.equals(this.created, avatarModeration.created) &&
        Objects.equals(this.targetAvatarId, avatarModeration.targetAvatarId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatarModerationType, created, targetAvatarId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvatarModeration {\n");
    sb.append("    avatarModerationType: ").append(toIndentedString(avatarModerationType)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    targetAvatarId: ").append(toIndentedString(targetAvatarId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("avatarModerationType", "created", "targetAvatarId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("avatarModerationType", "created", "targetAvatarId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AvatarModeration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AvatarModeration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AvatarModeration is not found in the empty JSON string", AvatarModeration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AvatarModeration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AvatarModeration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AvatarModeration.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `avatarModerationType`
      AvatarModerationType.validateJsonElement(jsonObj.get("avatarModerationType"));
      if (!jsonObj.get("targetAvatarId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `targetAvatarId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetAvatarId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AvatarModeration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AvatarModeration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AvatarModeration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AvatarModeration.class));

       return (TypeAdapter<T>) new TypeAdapter<AvatarModeration>() {
           @Override
           public void write(JsonWriter out, AvatarModeration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AvatarModeration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AvatarModeration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AvatarModeration
   * @throws IOException if the JSON string is invalid with respect to AvatarModeration
   */
  public static AvatarModeration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AvatarModeration.class);
  }

  /**
   * Convert an instance of AvatarModeration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

