/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.7
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The time unit used to specify how often a recurring event occurs.
 */
@JsonAdapter(CalendarEventFrequency.Adapter.class)
public enum CalendarEventFrequency {
  
  DAILY("daily"),
  
  MONTHLY("monthly"),
  
  WEEKLY("weekly"),
  
  YEARLY("yearly");

  private String value;

  CalendarEventFrequency(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CalendarEventFrequency fromValue(String value) {
    for (CalendarEventFrequency b : CalendarEventFrequency.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CalendarEventFrequency> {
    @Override
    public void write(final JsonWriter jsonWriter, final CalendarEventFrequency enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CalendarEventFrequency read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CalendarEventFrequency.fromValue(value);
    }
  }
}

