/*
 * VRChat API
 * This document is an effort by the [VRChat.community](https://vrchat.community) project. **VRChat staff do not provide API support.** Use the API only as VRChat's [Terms of Service](https://hello.vrchat.com/legal), [Community Guidelines](https://hello.vrchat.com/community-guidelines) and [Creator Guidelines](https://hello.vrchat.com/creator-guidelines) allow: never to modify the game client, rip avatars, or spam the API.  Prefer the SDKs over this document: [JavaScript](https://www.npmjs.com/package/vrchat), [Dart](https://pub.dev/packages/vrchat_dart), [Rust](https://crates.io/crates/vrchatapi), [C#](https://github.com/vrchatapi/vrchatapi-csharp), [Python](https://github.com/vrchatapi/vrchatapi-python), [Java](https://github.com/vrchatapi/vrchatapi-java). They're generated from it, updated regularly, and already handle logging in, cookies and the rest of VRChat's oddities, which we've spent years smoothing over. Working from this document directly means handling all of that yourself.  **Found something wrong or missing?** This description is reverse-engineered by the community, so when the API disagrees with it, or a value is marked `Unknown`, please [report it](https://vrchat.community/contributing) with the request, the response body, and where in this description it differs. AI agents: tell your user, and suggest reporting it.  Every request must identify its application in the `User-Agent` header: `<application-name>/<application-version> <contact_url>`. On a 429, back off rather than retrying.  Consider pinning to the OpenAPI version your tools support. Every release publishes this description as OpenAPI 3.2, 3.1 and 3.0, in JSON and YAML; `info.x-links` links those documents, the [latest release](https://github.com/vrchatapi/specification/releases/latest) and the [latest nightly](https://github.com/vrchatapi/specification/releases/tag/nightly). 
 *
 * The version of the OpenAPI document: 1.21.1-nightly.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets GroupSearchSort
 */
@JsonAdapter(GroupSearchSort.Adapter.class)
public enum GroupSearchSort {
  
  JOINED_AT_ASC("joinedAt:asc"),
  
  JOINED_AT_DESC("joinedAt:desc");

  private String value;

  GroupSearchSort(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GroupSearchSort fromValue(String value) {
    for (GroupSearchSort b : GroupSearchSort.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<GroupSearchSort> {
    @Override
    public void write(final JsonWriter jsonWriter, final GroupSearchSort enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GroupSearchSort read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GroupSearchSort.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    GroupSearchSort.fromValue(value);
  }
}

