/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.7.dev33
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * GroupTransferableRequirements
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GroupTransferableRequirements {
  public static final String SERIALIZED_NAME_GROUP_NOT_MONETIZED = "groupNotMonetized";
  @SerializedName(SERIALIZED_NAME_GROUP_NOT_MONETIZED)
  private Boolean groupNotMonetized = false;

  public static final String SERIALIZED_NAME_HAS_V_R_C_PLUS = "hasVRCPlus";
  @SerializedName(SERIALIZED_NAME_HAS_V_R_C_PLUS)
  private Boolean hasVRCPlus = false;

  public static final String SERIALIZED_NAME_HAS_VERIFIED_EMAIL = "hasVerifiedEmail";
  @SerializedName(SERIALIZED_NAME_HAS_VERIFIED_EMAIL)
  private Boolean hasVerifiedEmail = false;

  public static final String SERIALIZED_NAME_TARGET_CAN_OWN_MORE_GROUPS = "targetCanOwnMoreGroups";
  @SerializedName(SERIALIZED_NAME_TARGET_CAN_OWN_MORE_GROUPS)
  private Boolean targetCanOwnMoreGroups = false;

  public static final String SERIALIZED_NAME_TARGET_IS_GROUP_MEMBER = "targetIsGroupMember";
  @SerializedName(SERIALIZED_NAME_TARGET_IS_GROUP_MEMBER)
  private Boolean targetIsGroupMember = false;

  public GroupTransferableRequirements() {
  }

  public GroupTransferableRequirements groupNotMonetized(Boolean groupNotMonetized) {
    
    this.groupNotMonetized = groupNotMonetized;
    return this;
  }

   /**
   * Get groupNotMonetized
   * @return groupNotMonetized
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getGroupNotMonetized() {
    return groupNotMonetized;
  }


  public void setGroupNotMonetized(Boolean groupNotMonetized) {
    this.groupNotMonetized = groupNotMonetized;
  }


  public GroupTransferableRequirements hasVRCPlus(Boolean hasVRCPlus) {
    
    this.hasVRCPlus = hasVRCPlus;
    return this;
  }

   /**
   * Get hasVRCPlus
   * @return hasVRCPlus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getHasVRCPlus() {
    return hasVRCPlus;
  }


  public void setHasVRCPlus(Boolean hasVRCPlus) {
    this.hasVRCPlus = hasVRCPlus;
  }


  public GroupTransferableRequirements hasVerifiedEmail(Boolean hasVerifiedEmail) {
    
    this.hasVerifiedEmail = hasVerifiedEmail;
    return this;
  }

   /**
   * Get hasVerifiedEmail
   * @return hasVerifiedEmail
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getHasVerifiedEmail() {
    return hasVerifiedEmail;
  }


  public void setHasVerifiedEmail(Boolean hasVerifiedEmail) {
    this.hasVerifiedEmail = hasVerifiedEmail;
  }


  public GroupTransferableRequirements targetCanOwnMoreGroups(Boolean targetCanOwnMoreGroups) {
    
    this.targetCanOwnMoreGroups = targetCanOwnMoreGroups;
    return this;
  }

   /**
   * Get targetCanOwnMoreGroups
   * @return targetCanOwnMoreGroups
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getTargetCanOwnMoreGroups() {
    return targetCanOwnMoreGroups;
  }


  public void setTargetCanOwnMoreGroups(Boolean targetCanOwnMoreGroups) {
    this.targetCanOwnMoreGroups = targetCanOwnMoreGroups;
  }


  public GroupTransferableRequirements targetIsGroupMember(Boolean targetIsGroupMember) {
    
    this.targetIsGroupMember = targetIsGroupMember;
    return this;
  }

   /**
   * Get targetIsGroupMember
   * @return targetIsGroupMember
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getTargetIsGroupMember() {
    return targetIsGroupMember;
  }


  public void setTargetIsGroupMember(Boolean targetIsGroupMember) {
    this.targetIsGroupMember = targetIsGroupMember;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupTransferableRequirements groupTransferableRequirements = (GroupTransferableRequirements) o;
    return Objects.equals(this.groupNotMonetized, groupTransferableRequirements.groupNotMonetized) &&
        Objects.equals(this.hasVRCPlus, groupTransferableRequirements.hasVRCPlus) &&
        Objects.equals(this.hasVerifiedEmail, groupTransferableRequirements.hasVerifiedEmail) &&
        Objects.equals(this.targetCanOwnMoreGroups, groupTransferableRequirements.targetCanOwnMoreGroups) &&
        Objects.equals(this.targetIsGroupMember, groupTransferableRequirements.targetIsGroupMember);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupNotMonetized, hasVRCPlus, hasVerifiedEmail, targetCanOwnMoreGroups, targetIsGroupMember);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupTransferableRequirements {\n");
    sb.append("    groupNotMonetized: ").append(toIndentedString(groupNotMonetized)).append("\n");
    sb.append("    hasVRCPlus: ").append(toIndentedString(hasVRCPlus)).append("\n");
    sb.append("    hasVerifiedEmail: ").append(toIndentedString(hasVerifiedEmail)).append("\n");
    sb.append("    targetCanOwnMoreGroups: ").append(toIndentedString(targetCanOwnMoreGroups)).append("\n");
    sb.append("    targetIsGroupMember: ").append(toIndentedString(targetIsGroupMember)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("groupNotMonetized");
    openapiFields.add("hasVRCPlus");
    openapiFields.add("hasVerifiedEmail");
    openapiFields.add("targetCanOwnMoreGroups");
    openapiFields.add("targetIsGroupMember");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("groupNotMonetized");
    openapiRequiredFields.add("hasVRCPlus");
    openapiRequiredFields.add("hasVerifiedEmail");
    openapiRequiredFields.add("targetCanOwnMoreGroups");
    openapiRequiredFields.add("targetIsGroupMember");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GroupTransferableRequirements
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GroupTransferableRequirements.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupTransferableRequirements is not found in the empty JSON string", GroupTransferableRequirements.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GroupTransferableRequirements.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GroupTransferableRequirements` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GroupTransferableRequirements.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupTransferableRequirements.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupTransferableRequirements' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupTransferableRequirements> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupTransferableRequirements.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupTransferableRequirements>() {
           @Override
           public void write(JsonWriter out, GroupTransferableRequirements value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupTransferableRequirements read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GroupTransferableRequirements given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GroupTransferableRequirements
  * @throws IOException if the JSON string is invalid with respect to GroupTransferableRequirements
  */
  public static GroupTransferableRequirements fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupTransferableRequirements.class);
  }

 /**
  * Convert an instance of GroupTransferableRequirements to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

