/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.9
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * InfoPushDataSearch
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class InfoPushDataSearch {
  public static final String SERIALIZED_NAME_SEARCH_CONTENT = "searchContent";
  @SerializedName(SERIALIZED_NAME_SEARCH_CONTENT)
  @javax.annotation.Nullable
  private String searchContent;

  public static final String SERIALIZED_NAME_SEARCH_IN_FIELDS = "searchInFields";
  @SerializedName(SERIALIZED_NAME_SEARCH_IN_FIELDS)
  @javax.annotation.Nullable
  private String searchInFields;

  public static final String SERIALIZED_NAME_SEARCH_QUERY = "searchQuery";
  @SerializedName(SERIALIZED_NAME_SEARCH_QUERY)
  @javax.annotation.Nullable
  private String searchQuery;

  public static final String SERIALIZED_NAME_SEARCH_TAGS = "searchTags";
  @SerializedName(SERIALIZED_NAME_SEARCH_TAGS)
  @javax.annotation.Nullable
  private String searchTags;

  public static final String SERIALIZED_NAME_SORT_BY = "sortBy";
  @SerializedName(SERIALIZED_NAME_SORT_BY)
  @javax.annotation.Nullable
  private String sortBy;

  public InfoPushDataSearch() {
  }

  public InfoPushDataSearch searchContent(@javax.annotation.Nullable String searchContent) {
    this.searchContent = searchContent;
    return this;
  }

  /**
   * Get searchContent
   * @return searchContent
   */
  @javax.annotation.Nullable
  public String getSearchContent() {
    return searchContent;
  }

  public void setSearchContent(@javax.annotation.Nullable String searchContent) {
    this.searchContent = searchContent;
  }


  public InfoPushDataSearch searchInFields(@javax.annotation.Nullable String searchInFields) {
    this.searchInFields = searchInFields;
    return this;
  }

  /**
   * Get searchInFields
   * @return searchInFields
   */
  @javax.annotation.Nullable
  public String getSearchInFields() {
    return searchInFields;
  }

  public void setSearchInFields(@javax.annotation.Nullable String searchInFields) {
    this.searchInFields = searchInFields;
  }


  public InfoPushDataSearch searchQuery(@javax.annotation.Nullable String searchQuery) {
    this.searchQuery = searchQuery;
    return this;
  }

  /**
   * Get searchQuery
   * @return searchQuery
   */
  @javax.annotation.Nullable
  public String getSearchQuery() {
    return searchQuery;
  }

  public void setSearchQuery(@javax.annotation.Nullable String searchQuery) {
    this.searchQuery = searchQuery;
  }


  public InfoPushDataSearch searchTags(@javax.annotation.Nullable String searchTags) {
    this.searchTags = searchTags;
    return this;
  }

  /**
   * Get searchTags
   * @return searchTags
   */
  @javax.annotation.Nullable
  public String getSearchTags() {
    return searchTags;
  }

  public void setSearchTags(@javax.annotation.Nullable String searchTags) {
    this.searchTags = searchTags;
  }


  public InfoPushDataSearch sortBy(@javax.annotation.Nullable String sortBy) {
    this.sortBy = sortBy;
    return this;
  }

  /**
   * Get sortBy
   * @return sortBy
   */
  @javax.annotation.Nullable
  public String getSortBy() {
    return sortBy;
  }

  public void setSortBy(@javax.annotation.Nullable String sortBy) {
    this.sortBy = sortBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoPushDataSearch infoPushDataSearch = (InfoPushDataSearch) o;
    return Objects.equals(this.searchContent, infoPushDataSearch.searchContent) &&
        Objects.equals(this.searchInFields, infoPushDataSearch.searchInFields) &&
        Objects.equals(this.searchQuery, infoPushDataSearch.searchQuery) &&
        Objects.equals(this.searchTags, infoPushDataSearch.searchTags) &&
        Objects.equals(this.sortBy, infoPushDataSearch.sortBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchContent, searchInFields, searchQuery, searchTags, sortBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoPushDataSearch {\n");
    sb.append("    searchContent: ").append(toIndentedString(searchContent)).append("\n");
    sb.append("    searchInFields: ").append(toIndentedString(searchInFields)).append("\n");
    sb.append("    searchQuery: ").append(toIndentedString(searchQuery)).append("\n");
    sb.append("    searchTags: ").append(toIndentedString(searchTags)).append("\n");
    sb.append("    sortBy: ").append(toIndentedString(sortBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("searchContent", "searchInFields", "searchQuery", "searchTags", "sortBy"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InfoPushDataSearch
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InfoPushDataSearch.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in InfoPushDataSearch is not found in the empty JSON string", InfoPushDataSearch.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InfoPushDataSearch.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `InfoPushDataSearch` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("searchContent") != null && !jsonObj.get("searchContent").isJsonNull()) && !jsonObj.get("searchContent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `searchContent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("searchContent").toString()));
      }
      if ((jsonObj.get("searchInFields") != null && !jsonObj.get("searchInFields").isJsonNull()) && !jsonObj.get("searchInFields").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `searchInFields` to be a primitive type in the JSON string but got `%s`", jsonObj.get("searchInFields").toString()));
      }
      if ((jsonObj.get("searchQuery") != null && !jsonObj.get("searchQuery").isJsonNull()) && !jsonObj.get("searchQuery").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `searchQuery` to be a primitive type in the JSON string but got `%s`", jsonObj.get("searchQuery").toString()));
      }
      if ((jsonObj.get("searchTags") != null && !jsonObj.get("searchTags").isJsonNull()) && !jsonObj.get("searchTags").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `searchTags` to be a primitive type in the JSON string but got `%s`", jsonObj.get("searchTags").toString()));
      }
      if ((jsonObj.get("sortBy") != null && !jsonObj.get("sortBy").isJsonNull()) && !jsonObj.get("sortBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sortBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sortBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InfoPushDataSearch.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InfoPushDataSearch' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InfoPushDataSearch> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InfoPushDataSearch.class));

       return (TypeAdapter<T>) new TypeAdapter<InfoPushDataSearch>() {
           @Override
           public void write(JsonWriter out, InfoPushDataSearch value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InfoPushDataSearch read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InfoPushDataSearch given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InfoPushDataSearch
   * @throws IOException if the JSON string is invalid with respect to InfoPushDataSearch
   */
  public static InfoPushDataSearch fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InfoPushDataSearch.class);
  }

  /**
   * Convert an instance of InfoPushDataSearch to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

