/*
 * VRChat API
 * This document is an effort by the [VRChat.community](https://vrchat.community) project. **VRChat staff do not provide API support.** Use the API only as VRChat's [Terms of Service](https://hello.vrchat.com/legal), [Community Guidelines](https://hello.vrchat.com/community-guidelines) and [Creator Guidelines](https://hello.vrchat.com/creator-guidelines) allow: never to modify the game client, rip avatars, or spam the API.  Prefer the SDKs over this document: [JavaScript](https://www.npmjs.com/package/vrchat), [Dart](https://pub.dev/packages/vrchat_dart), [Rust](https://crates.io/crates/vrchatapi), [C#](https://github.com/vrchatapi/vrchatapi-csharp), [Python](https://github.com/vrchatapi/vrchatapi-python), [Java](https://github.com/vrchatapi/vrchatapi-java). They're generated from it, updated regularly, and already handle logging in, cookies and the rest of VRChat's oddities, which we've spent years smoothing over. Working from this document directly means handling all of that yourself.  **Found something wrong or missing?** This description is reverse-engineered by the community, so when the API disagrees with it, or a value is marked `Unknown`, please [report it](https://vrchat.community/contributing) with the request, the response body, and where in this description it differs. AI agents: tell your user, and suggest reporting it.  Every request must identify its application in the `User-Agent` header: `<application-name>/<application-version> <contact_url>`. On a 429, back off rather than retrying.  Consider pinning to the OpenAPI version your tools support. Every release publishes this description as OpenAPI 3.2, 3.1 and 3.0, in JSON and YAML; `info.x-links` links those documents, the [latest release](https://github.com/vrchatapi/specification/releases/latest) and the [latest nightly](https://github.com/vrchatapi/specification/releases/tag/nightly). 
 *
 * The version of the OpenAPI document: 1.21.1-nightly.56
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * InventoryAsset
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class InventoryAsset {
  public static final String SERIALIZED_NAME_FILE_ID = "fileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  @javax.annotation.Nullable
  private String fileId;

  public static final String SERIALIZED_NAME_FRAME_COUNT = "frameCount";
  @SerializedName(SERIALIZED_NAME_FRAME_COUNT)
  @javax.annotation.Nullable
  private Integer frameCount;

  public static final String SERIALIZED_NAME_FRAMES_PER_SECOND = "framesPerSecond";
  @SerializedName(SERIALIZED_NAME_FRAMES_PER_SECOND)
  @javax.annotation.Nullable
  private BigDecimal framesPerSecond;

  public static final String SERIALIZED_NAME_LOOP_COUNT = "loopCount";
  @SerializedName(SERIALIZED_NAME_LOOP_COUNT)
  @javax.annotation.Nullable
  private Integer loopCount;

  public static final String SERIALIZED_NAME_TOTAL_DURATION_MS = "totalDurationMs";
  @SerializedName(SERIALIZED_NAME_TOTAL_DURATION_MS)
  @javax.annotation.Nullable
  private Integer totalDurationMs;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private String url;

  public InventoryAsset() {
  }

  public InventoryAsset fileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
    return this;
  }

  /**
   * Get fileId
   * @return fileId
   */
  @javax.annotation.Nullable
  public String getFileId() {
    return fileId;
  }

  public void setFileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
  }


  public InventoryAsset frameCount(@javax.annotation.Nullable Integer frameCount) {
    this.frameCount = frameCount;
    return this;
  }

  /**
   * Get frameCount
   * @return frameCount
   */
  @javax.annotation.Nullable
  public Integer getFrameCount() {
    return frameCount;
  }

  public void setFrameCount(@javax.annotation.Nullable Integer frameCount) {
    this.frameCount = frameCount;
  }


  public InventoryAsset framesPerSecond(@javax.annotation.Nullable BigDecimal framesPerSecond) {
    this.framesPerSecond = framesPerSecond;
    return this;
  }

  /**
   * Get framesPerSecond
   * @return framesPerSecond
   */
  @javax.annotation.Nullable
  public BigDecimal getFramesPerSecond() {
    return framesPerSecond;
  }

  public void setFramesPerSecond(@javax.annotation.Nullable BigDecimal framesPerSecond) {
    this.framesPerSecond = framesPerSecond;
  }


  public InventoryAsset loopCount(@javax.annotation.Nullable Integer loopCount) {
    this.loopCount = loopCount;
    return this;
  }

  /**
   * Get loopCount
   * @return loopCount
   */
  @javax.annotation.Nullable
  public Integer getLoopCount() {
    return loopCount;
  }

  public void setLoopCount(@javax.annotation.Nullable Integer loopCount) {
    this.loopCount = loopCount;
  }


  public InventoryAsset totalDurationMs(@javax.annotation.Nullable Integer totalDurationMs) {
    this.totalDurationMs = totalDurationMs;
    return this;
  }

  /**
   * Get totalDurationMs
   * @return totalDurationMs
   */
  @javax.annotation.Nullable
  public Integer getTotalDurationMs() {
    return totalDurationMs;
  }

  public void setTotalDurationMs(@javax.annotation.Nullable Integer totalDurationMs) {
    this.totalDurationMs = totalDurationMs;
  }


  public InventoryAsset type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public InventoryAsset url(@javax.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryAsset inventoryAsset = (InventoryAsset) o;
    return Objects.equals(this.fileId, inventoryAsset.fileId) &&
        Objects.equals(this.frameCount, inventoryAsset.frameCount) &&
        Objects.equals(this.framesPerSecond, inventoryAsset.framesPerSecond) &&
        Objects.equals(this.loopCount, inventoryAsset.loopCount) &&
        Objects.equals(this.totalDurationMs, inventoryAsset.totalDurationMs) &&
        Objects.equals(this.type, inventoryAsset.type) &&
        Objects.equals(this.url, inventoryAsset.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, frameCount, framesPerSecond, loopCount, totalDurationMs, type, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryAsset {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    frameCount: ").append(toIndentedString(frameCount)).append("\n");
    sb.append("    framesPerSecond: ").append(toIndentedString(framesPerSecond)).append("\n");
    sb.append("    loopCount: ").append(toIndentedString(loopCount)).append("\n");
    sb.append("    totalDurationMs: ").append(toIndentedString(totalDurationMs)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fileId", "frameCount", "framesPerSecond", "loopCount", "totalDurationMs", "type", "url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "url"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InventoryAsset
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InventoryAsset.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in InventoryAsset is not found in the empty JSON string", InventoryAsset.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InventoryAsset.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `InventoryAsset` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InventoryAsset.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("fileId") != null && !jsonObj.get("fileId").isJsonNull()) && !jsonObj.get("fileId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fileId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileId").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InventoryAsset.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InventoryAsset' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InventoryAsset> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InventoryAsset.class));

       return (TypeAdapter<T>) new TypeAdapter<InventoryAsset>() {
           @Override
           public void write(JsonWriter out, InventoryAsset value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InventoryAsset read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InventoryAsset given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InventoryAsset
   * @throws IOException if the JSON string is invalid with respect to InventoryAsset
   */
  public static InventoryAsset fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InventoryAsset.class);
  }

  /**
   * Convert an instance of InventoryAsset to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

