/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.8
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * ModerationReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ModerationReport {
  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nonnull
  private String category;

  public static final String SERIALIZED_NAME_CONTENT_ID = "contentId";
  @SerializedName(SERIALIZED_NAME_CONTENT_ID)
  @javax.annotation.Nonnull
  private String contentId;

  public static final String SERIALIZED_NAME_CONTENT_NAME = "contentName";
  @SerializedName(SERIALIZED_NAME_CONTENT_NAME)
  @javax.annotation.Nonnull
  private String contentName;

  public static final String SERIALIZED_NAME_CONTENT_THUMBNAIL_IMAGE_URL = "contentThumbnailImageUrl";
  @SerializedName(SERIALIZED_NAME_CONTENT_THUMBNAIL_IMAGE_URL)
  @javax.annotation.Nullable
  private String contentThumbnailImageUrl;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_EVIDENCE_REQUIRED = "evidenceRequired";
  @SerializedName(SERIALIZED_NAME_EVIDENCE_REQUIRED)
  @javax.annotation.Nonnull
  private Boolean evidenceRequired;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nonnull
  private String reason;

  public static final String SERIALIZED_NAME_SUPPORT_REQUIRED = "supportRequired";
  @SerializedName(SERIALIZED_NAME_SUPPORT_REQUIRED)
  @javax.annotation.Nonnull
  private Boolean supportRequired;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public ModerationReport() {
  }

  public ModerationReport category(@javax.annotation.Nonnull String category) {
    this.category = category;
    return this;
  }

  /**
   * Valid values are the keys of the object &#x60;$.reportOptions[type]&#x60; from &#x60;GET /config&#x60;. Descriptions of these are found at &#x60;$.reportCategories[type]&#x60;.
   * @return category
   */
  @javax.annotation.Nonnull
  public String getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nonnull String category) {
    this.category = category;
  }


  public ModerationReport contentId(@javax.annotation.Nonnull String contentId) {
    this.contentId = contentId;
    return this;
  }

  /**
   * Get contentId
   * @return contentId
   */
  @javax.annotation.Nonnull
  public String getContentId() {
    return contentId;
  }

  public void setContentId(@javax.annotation.Nonnull String contentId) {
    this.contentId = contentId;
  }


  public ModerationReport contentName(@javax.annotation.Nonnull String contentName) {
    this.contentName = contentName;
    return this;
  }

  /**
   * Get contentName
   * @return contentName
   */
  @javax.annotation.Nonnull
  public String getContentName() {
    return contentName;
  }

  public void setContentName(@javax.annotation.Nonnull String contentName) {
    this.contentName = contentName;
  }


  public ModerationReport contentThumbnailImageUrl(@javax.annotation.Nullable String contentThumbnailImageUrl) {
    this.contentThumbnailImageUrl = contentThumbnailImageUrl;
    return this;
  }

  /**
   * Get contentThumbnailImageUrl
   * @return contentThumbnailImageUrl
   */
  @javax.annotation.Nullable
  public String getContentThumbnailImageUrl() {
    return contentThumbnailImageUrl;
  }

  public void setContentThumbnailImageUrl(@javax.annotation.Nullable String contentThumbnailImageUrl) {
    this.contentThumbnailImageUrl = contentThumbnailImageUrl;
  }


  public ModerationReport description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * The subjective reason for the report
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public ModerationReport evidenceRequired(@javax.annotation.Nonnull Boolean evidenceRequired) {
    this.evidenceRequired = evidenceRequired;
    return this;
  }

  /**
   * Get evidenceRequired
   * @return evidenceRequired
   */
  @javax.annotation.Nonnull
  public Boolean getEvidenceRequired() {
    return evidenceRequired;
  }

  public void setEvidenceRequired(@javax.annotation.Nonnull Boolean evidenceRequired) {
    this.evidenceRequired = evidenceRequired;
  }


  public ModerationReport id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public ModerationReport reason(@javax.annotation.Nonnull String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Valid values are the strings in the array &#x60;$.reportOptions[type][category]&#x60; from &#x60;GET /config&#x60;. Descriptions of these are found at &#x60;$.reportReasons[type]&#x60;.
   * @return reason
   */
  @javax.annotation.Nonnull
  public String getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nonnull String reason) {
    this.reason = reason;
  }


  public ModerationReport supportRequired(@javax.annotation.Nonnull Boolean supportRequired) {
    this.supportRequired = supportRequired;
    return this;
  }

  /**
   * Get supportRequired
   * @return supportRequired
   */
  @javax.annotation.Nonnull
  public Boolean getSupportRequired() {
    return supportRequired;
  }

  public void setSupportRequired(@javax.annotation.Nonnull Boolean supportRequired) {
    this.supportRequired = supportRequired;
  }


  public ModerationReport type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Valid values are the keys of the object &#x60;$.reportOptions&#x60; from &#x60;GET /config&#x60;.
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModerationReport moderationReport = (ModerationReport) o;
    return Objects.equals(this.category, moderationReport.category) &&
        Objects.equals(this.contentId, moderationReport.contentId) &&
        Objects.equals(this.contentName, moderationReport.contentName) &&
        Objects.equals(this.contentThumbnailImageUrl, moderationReport.contentThumbnailImageUrl) &&
        Objects.equals(this.description, moderationReport.description) &&
        Objects.equals(this.evidenceRequired, moderationReport.evidenceRequired) &&
        Objects.equals(this.id, moderationReport.id) &&
        Objects.equals(this.reason, moderationReport.reason) &&
        Objects.equals(this.supportRequired, moderationReport.supportRequired) &&
        Objects.equals(this.type, moderationReport.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, contentId, contentName, contentThumbnailImageUrl, description, evidenceRequired, id, reason, supportRequired, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModerationReport {\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    contentId: ").append(toIndentedString(contentId)).append("\n");
    sb.append("    contentName: ").append(toIndentedString(contentName)).append("\n");
    sb.append("    contentThumbnailImageUrl: ").append(toIndentedString(contentThumbnailImageUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    evidenceRequired: ").append(toIndentedString(evidenceRequired)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    supportRequired: ").append(toIndentedString(supportRequired)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("category", "contentId", "contentName", "contentThumbnailImageUrl", "description", "evidenceRequired", "id", "reason", "supportRequired", "type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("category", "contentId", "contentName", "contentThumbnailImageUrl", "description", "evidenceRequired", "id", "reason", "supportRequired", "type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModerationReport
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModerationReport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ModerationReport is not found in the empty JSON string", ModerationReport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ModerationReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ModerationReport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ModerationReport.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      if (!jsonObj.get("contentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentId").toString()));
      }
      if (!jsonObj.get("contentName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contentName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentName").toString()));
      }
      if ((jsonObj.get("contentThumbnailImageUrl") != null && !jsonObj.get("contentThumbnailImageUrl").isJsonNull()) && !jsonObj.get("contentThumbnailImageUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contentThumbnailImageUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentThumbnailImageUrl").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModerationReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModerationReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModerationReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModerationReport.class));

       return (TypeAdapter<T>) new TypeAdapter<ModerationReport>() {
           @Override
           public void write(JsonWriter out, ModerationReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModerationReport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ModerationReport given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModerationReport
   * @throws IOException if the JSON string is invalid with respect to ModerationReport
   */
  public static ModerationReport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModerationReport.class);
  }

  /**
   * Convert an instance of ModerationReport to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

