/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.8-nightly.20
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.vrchatapi.model.PlayerModerationType;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * PlayerModeration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PlayerModeration {
  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nonnull
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_SOURCE_DISPLAY_NAME = "sourceDisplayName";
  @SerializedName(SERIALIZED_NAME_SOURCE_DISPLAY_NAME)
  @javax.annotation.Nonnull
  private String sourceDisplayName;

  public static final String SERIALIZED_NAME_SOURCE_USER_ID = "sourceUserId";
  @SerializedName(SERIALIZED_NAME_SOURCE_USER_ID)
  @javax.annotation.Nonnull
  private String sourceUserId;

  public static final String SERIALIZED_NAME_TARGET_DISPLAY_NAME = "targetDisplayName";
  @SerializedName(SERIALIZED_NAME_TARGET_DISPLAY_NAME)
  @javax.annotation.Nonnull
  private String targetDisplayName;

  public static final String SERIALIZED_NAME_TARGET_USER_ID = "targetUserId";
  @SerializedName(SERIALIZED_NAME_TARGET_USER_ID)
  @javax.annotation.Nonnull
  private String targetUserId;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private PlayerModerationType type = PlayerModerationType.UNMUTE;

  public PlayerModeration() {
  }

  public PlayerModeration created(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
  }


  public PlayerModeration id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public PlayerModeration sourceDisplayName(@javax.annotation.Nonnull String sourceDisplayName) {
    this.sourceDisplayName = sourceDisplayName;
    return this;
  }

  /**
   * Get sourceDisplayName
   * @return sourceDisplayName
   */
  @javax.annotation.Nonnull
  public String getSourceDisplayName() {
    return sourceDisplayName;
  }

  public void setSourceDisplayName(@javax.annotation.Nonnull String sourceDisplayName) {
    this.sourceDisplayName = sourceDisplayName;
  }


  public PlayerModeration sourceUserId(@javax.annotation.Nonnull String sourceUserId) {
    this.sourceUserId = sourceUserId;
    return this;
  }

  /**
   * A users unique ID, usually in the form of &#x60;usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469&#x60;. Legacy players can have old IDs in the form of &#x60;8JoV9XEdpo&#x60;. The ID can never be changed.
   * @return sourceUserId
   */
  @javax.annotation.Nonnull
  public String getSourceUserId() {
    return sourceUserId;
  }

  public void setSourceUserId(@javax.annotation.Nonnull String sourceUserId) {
    this.sourceUserId = sourceUserId;
  }


  public PlayerModeration targetDisplayName(@javax.annotation.Nonnull String targetDisplayName) {
    this.targetDisplayName = targetDisplayName;
    return this;
  }

  /**
   * Get targetDisplayName
   * @return targetDisplayName
   */
  @javax.annotation.Nonnull
  public String getTargetDisplayName() {
    return targetDisplayName;
  }

  public void setTargetDisplayName(@javax.annotation.Nonnull String targetDisplayName) {
    this.targetDisplayName = targetDisplayName;
  }


  public PlayerModeration targetUserId(@javax.annotation.Nonnull String targetUserId) {
    this.targetUserId = targetUserId;
    return this;
  }

  /**
   * A users unique ID, usually in the form of &#x60;usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469&#x60;. Legacy players can have old IDs in the form of &#x60;8JoV9XEdpo&#x60;. The ID can never be changed.
   * @return targetUserId
   */
  @javax.annotation.Nonnull
  public String getTargetUserId() {
    return targetUserId;
  }

  public void setTargetUserId(@javax.annotation.Nonnull String targetUserId) {
    this.targetUserId = targetUserId;
  }


  public PlayerModeration type(@javax.annotation.Nonnull PlayerModerationType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public PlayerModerationType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull PlayerModerationType type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerModeration playerModeration = (PlayerModeration) o;
    return Objects.equals(this.created, playerModeration.created) &&
        Objects.equals(this.id, playerModeration.id) &&
        Objects.equals(this.sourceDisplayName, playerModeration.sourceDisplayName) &&
        Objects.equals(this.sourceUserId, playerModeration.sourceUserId) &&
        Objects.equals(this.targetDisplayName, playerModeration.targetDisplayName) &&
        Objects.equals(this.targetUserId, playerModeration.targetUserId) &&
        Objects.equals(this.type, playerModeration.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, id, sourceDisplayName, sourceUserId, targetDisplayName, targetUserId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerModeration {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceDisplayName: ").append(toIndentedString(sourceDisplayName)).append("\n");
    sb.append("    sourceUserId: ").append(toIndentedString(sourceUserId)).append("\n");
    sb.append("    targetDisplayName: ").append(toIndentedString(targetDisplayName)).append("\n");
    sb.append("    targetUserId: ").append(toIndentedString(targetUserId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("created", "id", "sourceDisplayName", "sourceUserId", "targetDisplayName", "targetUserId", "type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("created", "id", "sourceDisplayName", "sourceUserId", "targetDisplayName", "targetUserId", "type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PlayerModeration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlayerModeration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PlayerModeration is not found in the empty JSON string", PlayerModeration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlayerModeration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PlayerModeration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PlayerModeration.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("sourceDisplayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sourceDisplayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sourceDisplayName").toString()));
      }
      if (!jsonObj.get("sourceUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sourceUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sourceUserId").toString()));
      }
      if (!jsonObj.get("targetDisplayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `targetDisplayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetDisplayName").toString()));
      }
      if (!jsonObj.get("targetUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `targetUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetUserId").toString()));
      }
      // validate the required field `type`
      PlayerModerationType.validateJsonElement(jsonObj.get("type"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlayerModeration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlayerModeration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlayerModeration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlayerModeration.class));

       return (TypeAdapter<T>) new TypeAdapter<PlayerModeration>() {
           @Override
           public void write(JsonWriter out, PlayerModeration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlayerModeration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PlayerModeration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PlayerModeration
   * @throws IOException if the JSON string is invalid with respect to PlayerModeration
   */
  public static PlayerModeration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlayerModeration.class);
  }

  /**
   * Convert an instance of PlayerModeration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

