/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.7
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.vrchatapi.model.PurchaseContextData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * PurchaseProductListingRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PurchaseProductListingRequest {
  public static final String SERIALIZED_NAME_CONTEXT_DATA = "contextData";
  @SerializedName(SERIALIZED_NAME_CONTEXT_DATA)
  private PurchaseContextData contextData;

  public static final String SERIALIZED_NAME_LISTING_ID = "listingId";
  @SerializedName(SERIALIZED_NAME_LISTING_ID)
  private String listingId;

  public static final String SERIALIZED_NAME_LISTING_VARIANT_ID = "listingVariantId";
  @SerializedName(SERIALIZED_NAME_LISTING_VARIANT_ID)
  private String listingVariantId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity = 1;

  public static final String SERIALIZED_NAME_RECEIVER_ID = "receiverId";
  @SerializedName(SERIALIZED_NAME_RECEIVER_ID)
  private String receiverId;

  public static final String SERIALIZED_NAME_STACKABLE = "stackable";
  @SerializedName(SERIALIZED_NAME_STACKABLE)
  private Boolean stackable;

  public static final String SERIALIZED_NAME_TOTAL_PRICE = "totalPrice";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
  private Integer totalPrice;

  public PurchaseProductListingRequest() {
  }

  public PurchaseProductListingRequest contextData(PurchaseContextData contextData) {
    
    this.contextData = contextData;
    return this;
  }

   /**
   * Get contextData
   * @return contextData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PurchaseContextData getContextData() {
    return contextData;
  }


  public void setContextData(PurchaseContextData contextData) {
    this.contextData = contextData;
  }


  public PurchaseProductListingRequest listingId(String listingId) {
    
    this.listingId = listingId;
    return this;
  }

   /**
   * Get listingId
   * @return listingId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "prod_bfbc2315-247a-44d7-bfea-5237f8d56cb4", required = true, value = "")

  public String getListingId() {
    return listingId;
  }


  public void setListingId(String listingId) {
    this.listingId = listingId;
  }


  public PurchaseProductListingRequest listingVariantId(String listingVariantId) {
    
    this.listingVariantId = listingVariantId;
    return this;
  }

   /**
   * Get listingVariantId
   * @return listingVariantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "listvar_e8658b56-1662-436c-935a-afcf6a7d4fed", value = "")

  public String getListingVariantId() {
    return listingVariantId;
  }


  public void setListingVariantId(String listingVariantId) {
    this.listingVariantId = listingVariantId;
  }


  public PurchaseProductListingRequest quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * minimum: 1
   * maximum: 99
   * @return quantity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public PurchaseProductListingRequest receiverId(String receiverId) {
    
    this.receiverId = receiverId;
    return this;
  }

   /**
   * A users unique ID, usually in the form of &#x60;usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469&#x60;. Legacy players can have old IDs in the form of &#x60;8JoV9XEdpo&#x60;. The ID can never be changed.
   * @return receiverId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469", value = "A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.")

  public String getReceiverId() {
    return receiverId;
  }


  public void setReceiverId(String receiverId) {
    this.receiverId = receiverId;
  }


  public PurchaseProductListingRequest stackable(Boolean stackable) {
    
    this.stackable = stackable;
    return this;
  }

   /**
   * Get stackable
   * @return stackable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getStackable() {
    return stackable;
  }


  public void setStackable(Boolean stackable) {
    this.stackable = stackable;
  }


  public PurchaseProductListingRequest totalPrice(Integer totalPrice) {
    
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * minimum: 0
   * @return totalPrice
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getTotalPrice() {
    return totalPrice;
  }


  public void setTotalPrice(Integer totalPrice) {
    this.totalPrice = totalPrice;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseProductListingRequest purchaseProductListingRequest = (PurchaseProductListingRequest) o;
    return Objects.equals(this.contextData, purchaseProductListingRequest.contextData) &&
        Objects.equals(this.listingId, purchaseProductListingRequest.listingId) &&
        Objects.equals(this.listingVariantId, purchaseProductListingRequest.listingVariantId) &&
        Objects.equals(this.quantity, purchaseProductListingRequest.quantity) &&
        Objects.equals(this.receiverId, purchaseProductListingRequest.receiverId) &&
        Objects.equals(this.stackable, purchaseProductListingRequest.stackable) &&
        Objects.equals(this.totalPrice, purchaseProductListingRequest.totalPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextData, listingId, listingVariantId, quantity, receiverId, stackable, totalPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseProductListingRequest {\n");
    sb.append("    contextData: ").append(toIndentedString(contextData)).append("\n");
    sb.append("    listingId: ").append(toIndentedString(listingId)).append("\n");
    sb.append("    listingVariantId: ").append(toIndentedString(listingVariantId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    receiverId: ").append(toIndentedString(receiverId)).append("\n");
    sb.append("    stackable: ").append(toIndentedString(stackable)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("contextData");
    openapiFields.add("listingId");
    openapiFields.add("listingVariantId");
    openapiFields.add("quantity");
    openapiFields.add("receiverId");
    openapiFields.add("stackable");
    openapiFields.add("totalPrice");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("listingId");
    openapiRequiredFields.add("quantity");
    openapiRequiredFields.add("totalPrice");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PurchaseProductListingRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PurchaseProductListingRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PurchaseProductListingRequest is not found in the empty JSON string", PurchaseProductListingRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PurchaseProductListingRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PurchaseProductListingRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PurchaseProductListingRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `contextData`
      if (jsonObj.get("contextData") != null && !jsonObj.get("contextData").isJsonNull()) {
        PurchaseContextData.validateJsonObject(jsonObj.getAsJsonObject("contextData"));
      }
      if (!jsonObj.get("listingId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `listingId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("listingId").toString()));
      }
      if ((jsonObj.get("listingVariantId") != null && !jsonObj.get("listingVariantId").isJsonNull()) && !jsonObj.get("listingVariantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `listingVariantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("listingVariantId").toString()));
      }
      if ((jsonObj.get("receiverId") != null && !jsonObj.get("receiverId").isJsonNull()) && !jsonObj.get("receiverId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receiverId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receiverId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PurchaseProductListingRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PurchaseProductListingRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PurchaseProductListingRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PurchaseProductListingRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PurchaseProductListingRequest>() {
           @Override
           public void write(JsonWriter out, PurchaseProductListingRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PurchaseProductListingRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PurchaseProductListingRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PurchaseProductListingRequest
  * @throws IOException if the JSON string is invalid with respect to PurchaseProductListingRequest
  */
  public static PurchaseProductListingRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PurchaseProductListingRequest.class);
  }

 /**
  * Convert an instance of PurchaseProductListingRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

