/*
 * VRChat API Documentation
 *
 * The version of the OpenAPI document: 1.20.7
 * Contact: vrchatapi.lpv0t@aries.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.vrchatapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.github.vrchatapi.JSON;

/**
 * TiliaKyc
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TiliaKyc {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_KYC_ID = "kyc_id";
  @SerializedName(SERIALIZED_NAME_KYC_ID)
  private String kycId;

  public static final String SERIALIZED_NAME_KYC_REQUIREMENTS = "kyc_requirements";
  @SerializedName(SERIALIZED_NAME_KYC_REQUIREMENTS)
  private String kycRequirements;

  public static final String SERIALIZED_NAME_MATCH_CHECKS = "match_checks";
  @SerializedName(SERIALIZED_NAME_MATCH_CHECKS)
  private List<String> matchChecks = new ArrayList<>();

  public static final String SERIALIZED_NAME_PII_LEVEL = "pii_level";
  @SerializedName(SERIALIZED_NAME_PII_LEVEL)
  private String piiLevel;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<String> rules = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_TILIA_RETRY_RULE_CODE = "tilia_retry_rule_code";
  @SerializedName(SERIALIZED_NAME_TILIA_RETRY_RULE_CODE)
  private String tiliaRetryRuleCode;

  public TiliaKyc() {
  }

  public TiliaKyc accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * Tilia account identifier.
   * @return accountId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "acct_2YYRz9C5xbJWrhI5RLWPnwDLMyq", required = true, value = "Tilia account identifier.")

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public TiliaKyc kycId(String kycId) {
    
    this.kycId = kycId;
    return this;
  }

   /**
   * KYC verification identifier.
   * @return kycId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "kyc_2tDKpjafhPTG729ceA2oIcsQlWA", required = true, value = "KYC verification identifier.")

  public String getKycId() {
    return kycId;
  }


  public void setKycId(String kycId) {
    this.kycId = kycId;
  }


  public TiliaKyc kycRequirements(String kycRequirements) {
    
    this.kycRequirements = kycRequirements;
    return this;
  }

   /**
   * Requirement state reported by Tilia.
   * @return kycRequirements
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "NONE", required = true, value = "Requirement state reported by Tilia.")

  public String getKycRequirements() {
    return kycRequirements;
  }


  public void setKycRequirements(String kycRequirements) {
    this.kycRequirements = kycRequirements;
  }


  public TiliaKyc matchChecks(List<String> matchChecks) {
    
    this.matchChecks = matchChecks;
    return this;
  }

  public TiliaKyc addMatchChecksItem(String matchChecksItem) {
    this.matchChecks.add(matchChecksItem);
    return this;
  }

   /**
   * Match checks returned by Tilia.
   * @return matchChecks
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Match checks returned by Tilia.")

  public List<String> getMatchChecks() {
    return matchChecks;
  }


  public void setMatchChecks(List<String> matchChecks) {
    this.matchChecks = matchChecks;
  }


  public TiliaKyc piiLevel(String piiLevel) {
    
    this.piiLevel = piiLevel;
    return this;
  }

   /**
   * PII verification level.
   * @return piiLevel
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "FULL", required = true, value = "PII verification level.")

  public String getPiiLevel() {
    return piiLevel;
  }


  public void setPiiLevel(String piiLevel) {
    this.piiLevel = piiLevel;
  }


  public TiliaKyc rules(List<String> rules) {
    
    this.rules = rules;
    return this;
  }

  public TiliaKyc addRulesItem(String rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Additional rules returned by Tilia.
   * @return rules
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Additional rules returned by Tilia.")

  public List<String> getRules() {
    return rules;
  }


  public void setRules(List<String> rules) {
    this.rules = rules;
  }


  public TiliaKyc state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * Overall KYC state.
   * @return state
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "ACCEPT", required = true, value = "Overall KYC state.")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public TiliaKyc tiliaRetryRuleCode(String tiliaRetryRuleCode) {
    
    this.tiliaRetryRuleCode = tiliaRetryRuleCode;
    return this;
  }

   /**
   * Retry rule code returned by Tilia, if any.
   * @return tiliaRetryRuleCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Retry rule code returned by Tilia, if any.")

  public String getTiliaRetryRuleCode() {
    return tiliaRetryRuleCode;
  }


  public void setTiliaRetryRuleCode(String tiliaRetryRuleCode) {
    this.tiliaRetryRuleCode = tiliaRetryRuleCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TiliaKyc tiliaKyc = (TiliaKyc) o;
    return Objects.equals(this.accountId, tiliaKyc.accountId) &&
        Objects.equals(this.kycId, tiliaKyc.kycId) &&
        Objects.equals(this.kycRequirements, tiliaKyc.kycRequirements) &&
        Objects.equals(this.matchChecks, tiliaKyc.matchChecks) &&
        Objects.equals(this.piiLevel, tiliaKyc.piiLevel) &&
        Objects.equals(this.rules, tiliaKyc.rules) &&
        Objects.equals(this.state, tiliaKyc.state) &&
        Objects.equals(this.tiliaRetryRuleCode, tiliaKyc.tiliaRetryRuleCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, kycId, kycRequirements, matchChecks, piiLevel, rules, state, tiliaRetryRuleCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TiliaKyc {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    kycId: ").append(toIndentedString(kycId)).append("\n");
    sb.append("    kycRequirements: ").append(toIndentedString(kycRequirements)).append("\n");
    sb.append("    matchChecks: ").append(toIndentedString(matchChecks)).append("\n");
    sb.append("    piiLevel: ").append(toIndentedString(piiLevel)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    tiliaRetryRuleCode: ").append(toIndentedString(tiliaRetryRuleCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("account_id");
    openapiFields.add("kyc_id");
    openapiFields.add("kyc_requirements");
    openapiFields.add("match_checks");
    openapiFields.add("pii_level");
    openapiFields.add("rules");
    openapiFields.add("state");
    openapiFields.add("tilia_retry_rule_code");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("account_id");
    openapiRequiredFields.add("kyc_id");
    openapiRequiredFields.add("kyc_requirements");
    openapiRequiredFields.add("match_checks");
    openapiRequiredFields.add("pii_level");
    openapiRequiredFields.add("rules");
    openapiRequiredFields.add("state");
    openapiRequiredFields.add("tilia_retry_rule_code");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TiliaKyc
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TiliaKyc.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TiliaKyc is not found in the empty JSON string", TiliaKyc.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TiliaKyc.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TiliaKyc` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TiliaKyc.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if (!jsonObj.get("kyc_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kyc_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kyc_id").toString()));
      }
      if (!jsonObj.get("kyc_requirements").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kyc_requirements` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kyc_requirements").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("match_checks") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("match_checks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `match_checks` to be an array in the JSON string but got `%s`", jsonObj.get("match_checks").toString()));
      }
      if (!jsonObj.get("pii_level").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pii_level` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pii_level").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("rules") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("rules").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `rules` to be an array in the JSON string but got `%s`", jsonObj.get("rules").toString()));
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if (!jsonObj.get("tilia_retry_rule_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tilia_retry_rule_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tilia_retry_rule_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TiliaKyc.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TiliaKyc' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TiliaKyc> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TiliaKyc.class));

       return (TypeAdapter<T>) new TypeAdapter<TiliaKyc>() {
           @Override
           public void write(JsonWriter out, TiliaKyc value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TiliaKyc read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TiliaKyc given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TiliaKyc
  * @throws IOException if the JSON string is invalid with respect to TiliaKyc
  */
  public static TiliaKyc fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TiliaKyc.class);
  }

 /**
  * Convert an instance of TiliaKyc to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

